from . import it_asset_views
from . import software_license_views
from . import maintenance_contract_views
from . import technician_views
from . import asset_category_views
from . import location_views
from . import intervention_views
from . import ticket_views
from . import menus